include_recipe "apt"

package "build-essential"
package "curl"
package "debootstrap"
package "genisoimage"
package "joe"
package "libsqlite3-dev"
package "libxml2-dev"
package "libxslt-dev"
package "tmux"
package "vim"
